export const CARD_THEMES = [
    {
        id: "default",
        name: "Classic Blue",
        description: "The original reliable look",
        price: 0,
        gradient: "linear-gradient(to bottom right, #1a1f71, #004e92)",
        textColor: "text-white",
        borderColor: "border-white/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "gold",
        name: "Gold Prestige",
        description: "For the high achievers",
        price: 2000,
        gradient: "linear-gradient(to bottom right, #BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
        textColor: "text-yellow-950",
        borderColor: "border-yellow-900/20",
        chipColor: "from-slate-300 to-slate-400",
    },
    {
        id: "platinum",
        name: "Platinum Elite",
        description: "Sleek and sophisticated",
        price: 5000,
        gradient: "linear-gradient(to bottom right, #E6E6E6, #ffffff, #B3B3B3)",
        textColor: "text-slate-800",
        borderColor: "border-slate-400/30",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "rose_gold",
        name: "Rose Gold",
        description: "Elegant and trendy",
        price: 1500,
        gradient: "linear-gradient(to bottom right, #B86E6E, #F2C6C6, #E6A5A5)",
        textColor: "text-rose-950",
        borderColor: "border-rose-900/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "cyberpunk",
        name: "Cyberpunk",
        description: "High-tech neon vibes",
        price: 1000,
        gradient: "linear-gradient(to bottom right, #2b213a, #111827, #4c1d95)",
        textColor: "text-cyan-400",
        borderColor: "border-cyan-500/50",
        chipColor: "from-cyan-400 to-purple-500",
    },
    {
        id: "forest",
        name: "Deep Forest",
        description: "Natural abundance",
        price: 800,
        gradient: "linear-gradient(to bottom right, #134e5e, #71b280)",
        textColor: "text-white",
        borderColor: "border-white/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "midnight",
        name: "Midnight Black",
        description: "Stealth wealth",
        price: 1200,
        gradient: "linear-gradient(to bottom right, #000000, #434343)",
        textColor: "text-white",
        borderColor: "border-white/10",
        chipColor: "from-slate-200 to-slate-400",
    },
];
