export const CARD_THEMES = [
    {
        id: "default",
        name: "Classic Blue",
        description: "The original reliable look",
        price: 0,
        gradient: "linear-gradient(to bottom right, #1a1f71, #004e92)",
        textColor: "text-white",
        borderColor: "border-white/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "gold",
        name: "Gold Prestige",
        description: "For the high achievers",
        price: 2000,
        gradient: "linear-gradient(to bottom right, #BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
        textColor: "text-yellow-950",
        borderColor: "border-yellow-900/20",
        chipColor: "from-slate-300 to-slate-400",
    },
    {
        id: "platinum",
        name: "Platinum Elite",
        description: "Sleek and sophisticated",
        price: 5000,
        gradient: "linear-gradient(to bottom right, #E6E6E6, #ffffff, #B3B3B3)",
        textColor: "text-slate-800",
        borderColor: "border-slate-400/30",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "rose_gold",
        name: "Rose Gold",
        description: "Elegant and trendy",
        price: 1500,
        gradient: "linear-gradient(to bottom right, #B86E6E, #F2C6C6, #E6A5A5)",
        textColor: "text-rose-950",
        borderColor: "border-rose-900/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "cyberpunk",
        name: "Cyberpunk",
        description: "High-tech neon vibes",
        price: 1000,
        gradient: "linear-gradient(to bottom right, #2b213a, #111827, #4c1d95)",
        textColor: "text-cyan-400",
        borderColor: "border-cyan-500/50",
        chipColor: "from-cyan-400 to-purple-500",
    },
    {
        id: "forest",
        name: "Deep Forest",
        description: "Natural abundance",
        price: 800,
        gradient: "linear-gradient(to bottom right, #134e5e, #71b280)",
        textColor: "text-white",
        borderColor: "border-white/20",
        chipColor: "from-yellow-200 to-yellow-500",
    },
    {
        id: "midnight",
        name: "Midnight Black",
        description: "Stealth wealth",
        price: 1200,
        gradient: "linear-gradient(to bottom right, #000000, #434343)",
        textColor: "text-white",
        borderColor: "border-white/10",
        chipColor: "from-slate-200 to-slate-400",
    },
];

export const MARVEL_THEMES = [
    {
        id: "marvel_ironman",
        name: "Iron Man",
        description: "I am Iron Man",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #7B0000, #D4AF37)", // Fallback
        image: "/card-themes/iron-man.png",
        textColor: "text-white",
        borderColor: "border-yellow-500/50",
        chipColor: "from-cyan-200 to-cyan-400", // Arc reactor vibes
    },
    {
        id: "marvel_cap",
        name: "Captain America",
        description: "The First Avenger",
        price: 2800,
        gradient: "linear-gradient(to bottom right, #002244, #8B0000, #FFFFF0)",
        image: "/card-themes/captain-america.png",
        textColor: "text-white",
        borderColor: "border-blue-400/50",
        chipColor: "from-blue-400 to-red-500",
    },
    {
        id: "marvel_hulk",
        name: "The Hulk",
        description: "Smash!",
        price: 2800,
        gradient: "linear-gradient(to bottom right, #4B6F44, #32CD32)",
        image: "/card-themes/hulk.png",
        textColor: "text-white",
        borderColor: "border-green-400/50",
        chipColor: "from-green-400 to-purple-500",
    },
    {
        id: "marvel_widow",
        name: "Black Widow",
        description: "Master Spy",
        price: 2500,
        gradient: "linear-gradient(to bottom right, #000000, #8B0000)",
        image: "/card-themes/black-widow.png",
        textColor: "text-white",
        borderColor: "border-red-500/50",
        chipColor: "from-red-500 to-gray-800",
    },
    {
        id: "marvel_thor",
        name: "Thor",
        description: "God of Thunder",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #1F2937, #9CA3AF, #FCD34D)",
        image: "/card-themes/thor.jpg",
        textColor: "text-white",
        borderColor: "border-yellow-400/50",
        chipColor: "from-blue-300 to-yellow-300", // Lightning
    },
    {
        id: "marvel_loki",
        name: "Loki",
        description: "God of Mischief",
        price: 2900,
        gradient: "linear-gradient(to bottom right, #006400, #FFD700)",
        image: "/card-themes/loki.jpg",
        textColor: "text-yellow-100",
        borderColor: "border-green-500/50",
        chipColor: "from-green-400 to-yellow-500",
    },
    {
        id: "marvel_spiderman",
        name: "Spider-Man",
        description: "Friendly Neighborhood",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #C8102E, #2F80ED)",
        image: "/card-themes/spiderman.png",
        textColor: "text-white",
        borderColor: "border-blue-500/50",
        chipColor: "from-red-500 to-blue-500",
    },
    {
        id: "marvel_strange",
        name: "Doctor Strange",
        description: "Sorcerer Supreme",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #4B0082, #FF4500)",
        image: "/card-themes/doctor-strange.jpg",
        textColor: "text-white",
        borderColor: "border-purple-500/50",
        chipColor: "from-purple-500 to-orange-500",
    }
];

export const ANIME_THEMES = [
    {
        id: "anime_naruto",
        name: "Naruto Uzumaki",
        description: "Dattebayo!",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #FFA500, #000000)",
        image: "/card-themes/naruto.png",
        textColor: "text-white",
        borderColor: "border-orange-500/50",
        chipColor: "from-orange-400 to-yellow-500",
    },
    {
        id: "anime_luffy",
        name: "Monkey D. Luffy",
        description: "King of Pirates",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #FF0000, #FFD700)",
        image: "/card-themes/one-piece.jpg",
        textColor: "text-white",
        borderColor: "border-red-500/50",
        chipColor: "from-yellow-400 to-red-500",
    },
    {
        id: "anime_aot",
        name: "Attack on Titan",
        description: "Sasageyo!",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #556B2F, #8B4513)",
        image: "/card-themes/aot.jpg",
        textColor: "text-white",
        borderColor: "border-green-800/50",
        chipColor: "from-green-700 to-yellow-700",
    },
    {
        id: "anime_demonslayer",
        name: "Demon Slayer",
        description: "Hashira",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #000000, #3CB371)",
        image: "/card-themes/demon-slayer.png",
        textColor: "text-white",
        borderColor: "border-green-500/50",
        chipColor: "from-green-400 to-black",
    },
    {
        id: "anime_sololeveling",
        name: "Solo Leveling",
        description: "Shadow Monarch",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #000000, #4B0082)",
        image: "/card-themes/solo-leveling.png",
        textColor: "text-blue-100",
        borderColor: "border-purple-500/50",
        chipColor: "from-purple-500 to-blue-500",
    },
    {
        id: "anime_deathnote",
        name: "Death Note",
        description: "I Am Justice",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #000000, #8B0000)",
        image: "/card-themes/death-note.png",
        textColor: "text-white",
        borderColor: "border-red-600/50",
        chipColor: "from-red-600 to-black",
    },
    {
        id: "anime_spyxfamily",
        name: "Spy x Family",
        description: "Operation Strix",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #2E8B57, #FFC0CB)",
        image: "/card-themes/spy-x-family.png",
        textColor: "text-white",
        borderColor: "border-green-400/50",
        chipColor: "from-green-400 to-pink-400",
    },
    {
        id: "anime_dandadan",
        name: "Dandadan",
        description: "Occult x Sci-Fi",
        price: 3000,
        gradient: "linear-gradient(to bottom right, #800080, #FF00FF)",
        image: "/card-themes/dandadan.jpg",
        textColor: "text-white",
        borderColor: "border-pink-500/50",
        chipColor: "from-purple-500 to-pink-500",
    }
];

export const ALL_THEMES = [...CARD_THEMES, ...MARVEL_THEMES, ...ANIME_THEMES];
