export const FINANCIAL_QUOTES = [
    "Discipline is the bridge between goals and accomplishment.",
    "Do not save what is left after spending, but spend what is left after saving. – Warren Buffett",
    "A budget is telling your money where to go instead of wondering where it went. – Dave Ramsey",
    "Financial freedom is available to those who learn about it and work for it. – Robert Kiyosaki",
    "Beware of little expenses. A small leak will sink a great ship. – Benjamin Franklin",
    "The art is not in making money, but in keeping it.",
    "It’s not your salary that makes you rich, it’s your spending habits. – Charles A. Jaffe",
    "Rich people stay rich by living like they’re broke. Broke people stay broke by living like they’re rich.",
    "Money is a terrible master but an excellent servant. – P.T. Barnum",
    "You must gain control over your money or the lack of it will forever control you. – Dave Ramsey",
    "The quickest way to double your money is to fold it over and put it back in your pocket. – Will Rogers",
    "Money grows on the tree of persistence.",
    "Don’t let making a living prevent you from making a life. – John Wooden",
    "Wealth is the ability to fully experience life. – Henry David Thoreau",
    "The goal isn’t more money. The goal is living life on your terms. – Chris Brogan",
    "Being broke is hard. Becoming wealthy is hard. Choose your hard.",
    "Invest in yourself. It pays the best interest. – Benjamin Franklin",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work. – Thomas Edison",
    "Empty pockets never held anyone back. Only empty heads and empty hearts can do that. – Norman Vincent Peale",
    "A penny saved is a penny earned. – Benjamin Franklin",
    "Never spend your money before you have it. – Thomas Jefferson",
    "If you buy things you do not need, soon you will have to sell things you need. – Warren Buffett",
    "Formal education will make you a living; self-education will make you a fortune. – Jim Rohn",
    "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make. – Dave Ramsey",
    "Wealth consists not in having great possessions, but in having few wants. – Epictetus",
    "Money often costs too much. – Ralph Waldo Emerson",
    "Every time you borrow money, you're robbing your future self. – Nathan W. Morris",
    "To get rich, you have to be making money while you're asleep. – David Bailey",
    "The stock market is designed to transfer money from the Active to the Patient. – Warren Buffett",
    "Live within your means and save for the future.",
    "By failing to prepare, you are preparing to fail. – Benjamin Franklin",
    "The safe way to double your money is to fold it over once and put it in your pocket. – Frank Hubbard",
    "Investing should be more like watching paint dry or watching grass grow. – Paul Samuelson",
    "Too many people spend money they haven't earned, to buy things they don't want, to impress people they don't like. – Will Rogers",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. – Winston Churchill",
    "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
    "Don't stay in bed, unless you can make money in bed. – George Burns",
    "I'd rather have a rose on my table than a diamond on my neck. – Emma Goldman",
    "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any. – Thomas Jefferson",
    "If you want to reap financial blessings, you have to sow financially. – Joel Osteen",
    "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver. – Ayn Rand",
    "Financial security and independence are like a three-legged stool resting on savings, insurance, and investments.",
    "The trick is to stop thinking of it as 'your' money. – IRS Auditor",
    "Time is more reliable than money. – Proverb",
    "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs. – Zig Ziglar",
    "You can't connect the dots looking forward; you can only connect them looking backwards. – Steve Jobs",
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "Your time is limited, so don't waste it living someone else's life. – Steve Jobs",
    "Stay hungry, stay foolish. – Steve Jobs",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Money is like manure. You have to spread it around or it smells. – J. Paul Getty",
    "I believe that through knowledge and discipline, financial peace is possible for all of us. – Dave Ramsey",
    "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought, and so broadens the mind. – T.T. Munger",
    "Frugality includes all the other virtues. – Cicero",
    "He who buys what he does not need, steals from himself. – Swedish Proverb",
    "Money is a guarantee that we may have what we want in the future. Though we need nothing at the moment it insures the possibility of satisfying a new desire when it arises. – Aristotle",
    "Capital as such is not evil; it is its wrong use that is evil. Capital in some form or other will always be needed. – Gandhi",
    "Annual income twenty pounds, annual expenditure nineteen six, result happiness. Annual income twenty pounds, annual expenditure twenty pound ought and six, result misery. – Charles Dickens",
    "Fortune sides with him who dares. – Virgil"
];
